openapi: 3.0.0
info:
  title: vinyl-api
  version: 1.0.0
  contact:
    name: Dardan Rrafshi
    url: 'https://github.com/DonColon/vinyl-api-spec/issues'
    email: dardan.rrafshi@gmail.com
  license:
    name: Apache 2.0
    url: 'https://github.com/DonColon/vinyl-api-spec/blob/master/LICENSE'
  description: The Specification of the RESTful API for vinyl
servers:
  - url: 'http://localhost:3000'
    description: Development
paths: {}
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
  securitySchemes: {}
